### ISSUE TITLE
While running ./setupEnvironment.sh gives error

### ISSUE THREAD

**Issue by KrishnaAnanthi** [awslabs/serverless-photo-recognition#10]
After getting code to my local, i tried to run the command..i am getting this error.. i have installed aws client and awslogs..do i need to install anything else ?
D:\aPaaS\Aws\projects\serverless-photo-recognition-master\setup>./setupEnvironment.sh
'.' is not recognized as an internal or external command,

**Comment by KrishnaAnanthi** [comment]
now i run just setupEnvironment.sh and got the build failed with the below error.

:compileKotline: D:\aPaaS\Aws\projects\serverless-photo-recognition-master\src\main\kotlin\com\budilov\db\ESPictureService.kt: (17, 13): Unresolved reference: time
e: D:\aPaaS\Aws\projects\serverless-photo-recognition-master\src\main\kotlin\com\budilov\db\ESPictureService.kt: (18, 13): Unresolved reference: time
e: D:\aPaaS\Aws\projects\serverless-photo-recognition-master\src\main\kotlin\com\budilov\db\ESPictureService.kt: (35, 23): Unresolved reference: LocalDateTime
e: D:\aPaaS\Aws\projects\serverless-photo-recognition-master\src\main\kotlin\com\budilov\db\ESPictureService.kt: (35, 41): Unresolved reference: ZoneOffset
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


Waiting for the ES domain rekognition20170313144426 to finish processing. Sleeping...
Waiting for the ES domain rekognition20170313144426 to finish processing. Sleeping...
Waiting for the ES domain rekognition20170313144426 to finish processing. Sleeping...

**Comment by vbudilov** [comment]
Hi @KrishnaAnanhti , 

It looks like you're running from a Windows machine. The setup script needs bash to run. I haven't tested it on Windows, so it might not work. 

Vladimir
