### ISSUE TITLE
Properties.kt is empty (or sometimes incomplete)

### ISSUE THREAD

**Issue by tomhoag** [awslabs/serverless-photo-recognition#2]
When running the setEnvironment.sh, sometimes the Properties.kt file ends up empty (i.e. file size = 0)  and sometimes is is nearly complete but is missing a valid value for _ES_SERVICE_URL e.g. 

`    val _ES_SERVICE_URL = "https://None"
` 

I have not been able to track down the source of the file empty problem, but I suspect that populating the ES_SERVICE_URL is a timing issue? 

`ES_ENDPOINT=$(aws es describe-elasticsearch-domain --domain-name ${ES_DOMAIN_NAME} --query "DomainStatus.Endpoint" --output text)`
 
is being executed immediately after the ES search domain is completed processing and is returning None.   Maybe there is some intermediate state prior to the DomainStatus.Endpoint being populated??

**Comment by vbudilov** [comment]
Hi @tomhoag , 

Please pull the latest code. I made an update recently -- at this time the script waits for the ES domain to be created -- that's when the ES url is available. 

Let me know if that works. 

Vladimir

**Comment by tomhoag** [comment]
Hi Vladimir

I don't see an update to the while statement.  I've created a fork and made a change to 

`while [ 'None' == $(aws es describe-elasticsearch-domain --domain-name ${ES_DOMAIN_NAME} --query  "DomainStatus.Endpoint" --output text) ];`

I'm going to close this issue and open a pull request with the above change.

Thanks!

**Comment by vbudilov** [comment]
You should see the following while loop, if not you have the older version
of the code:

## We need the endpoint url now, but the ES domain is most-likely
processing right now. Let's wait until it finishes
while [ 'True' == $(aws es describe-elasticsearch-domain --domain-name
${ES_DOMAIN_NAME} --query "DomainStatus.Processing" --output text) ];
do
    echo "Waiting for the Elasticsearch domain to finish processing.
Sleeping..."
    sleep 30
done

**Comment by tomhoag** [comment]
I do have that version of the code -- I'm suggesting that the current while statement

`while [ 'True' == $(aws es describe-elasticsearch-domain --domain-name ${ES_DOMAIN_NAME} --query  "DomainStatus.Processing" --output text) ];`

 be changed to

`while [ 'None' == $(aws es describe-elasticsearch-domain --domain-name ${ES_DOMAIN_NAME} --query  "DomainStatus.Endpoint" --output text) ];`

This avoids the problem in which _ES_SERVICE_URL was getting resolved to "https://None" in Properties.kt

**Comment by vbudilov** [comment]
I'll have to take a look. It was resolving to None when I didn't have the while loop but from what I understood once the Processing is finished the url is assigned, so it should never be none. I'll need to do some research.
