### ISSUE TITLE
Use of sed -i in setupEnvironment.sh

### ISSUE THREAD

**Issue by tomhoag** [awslabs/serverless-photo-recognition#6]
Hi Vladimir 

When I run setupEnvironment.sh on OS X (10.12.3), the script errors out when attempting to _sed_ the values into Properties.kt

```
sed: 1: "../src/main/kotlin/com/ ...": invalid command code .
sed: 1: "../src/main/kotlin/com/ ...": invalid command code .
sed: 1: "../src/main/kotlin/com/ ...": invalid command code .
sed: 1: "../src/main/kotlin/com/ ...": invalid command code .
sed: 1: "../src/main/kotlin/com/ ...": invalid command code .
sed: 1: "../src/main/kotlin/com/ ...": invalid command code .
```
I *think* this is because _sed_ on OS X expects there to be a file extension immediately after the -i 

instead of 

`sed  -i 's#REGION_REPLACE_ME#'${REGION}'#g' ../src/main/kotlin/com/budilov/Properties.kt
`
OSX needs

`sed  -i.tmp 's#REGION_REPLACE_ME#'${REGION}'#g' ../src/main/kotlin/com/budilov/Properties.kt
`

Previously, the substitution was handled by piping all of the sed statements together -- not sure why that changed?  

Anyway, I'm happy to make the change and provide a pull request, but I'm not sure what the behavior of the change will be on other OS's?

Update: changing -i to -i.tmp does fix the problem on OS X

**Comment by vbudilov** [comment]
I've made the change and checked it in...unfortunate discrepancy.
